package br.com.doit.rxworld.enums;

public enum PaymentStatus {
	AUTHORIZED,
    AUTHORIZING,
    CANCELED,
    CANCELING,
    CAPTURED,
    CAPTURING,
    CREATED,
    ERROR_AUTHORIZING,
    ERROR_CANCELING,
    ERROR_CAPTURING,
    ERROR_REVERSING,
    FRAUD_APROVED,
    FRAUD_CANCELED,
    FRAUD_CONFIRMED,
    FRAUD_ERROR,
    FRAUD_PROCESSING,
    NOT_AUTHORIZED,
    PAYMENT_PROCESSING,
    REVERSED,
    REVERSING;
}
