CREATE TABLE web_store (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organization VARCHAR(255),
  doit_web_store_id INTEGER,
  doit_url VARCHAR(255),
  rxworld_url VARCHAR(255),
  client_id VARCHAR(255),
  client_secret VARCHAR(255),
  username VARCHAR(255),
  password VARCHAR(255),
  order_criterias VARCHAR(255) DEFAULT 'orderplaced',
  CONSTRAINT pk_web_store PRIMARY KEY (id)
);

ALTER TABLE web_store ADD CONSTRAINT uq_web_store__doit_web_store_id__organization UNIQUE (doit_web_store_id, organization);
