CREATE TABLE product (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  web_store_id INTEGER NOT NULL,
  doit_product_id INTEGER,
  rxworld_id INTEGER,
  date_created DATE,
  date_updated DATE,
  sku VARCHAR(255),
  CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product ADD CONSTRAINT fk_product__web_store_id FOREIGN KEY (web_store_id) REFERENCES web_store;
